# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os


# -- Project information -----------------------------------------------------

project = 'Lua Functional'
copyright = '2013-2021, Roman Tsisyk'
author = 'Roman Tsisyk'

# The short X.Y version
version = '0.1'

# The full version, including alpha/beta/rc tags
release = '0.1.3'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
]

# Source file suffixes and the parsers used for them. Markdown files are
# produced by emmylua_doc_cli and parsed with MyST.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# Generate stable anchors for section headings, so that the cross references
# between the generated API pages (e.g. "See also: [span](slicing.md#fun-span)")
# resolve.
myst_heading_anchors = 3

# emmylua_doc_cli emits decorative "---" separators after headings and
# pseudo-Lua type signatures in code blocks; both cause non-fatal warnings.
suppress_warnings = [
    'docutils',
    'misc.highlighting_failure',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'haiku'

# The base URL used for the canonical link (set by CI; empty for local builds)
html_baseurl = os.environ.get('SITE_URL', '')

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'logo.png'

# The haiku theme, unlike newer Sphinx, checks the `logo` context variable
# (Sphinx itself only provides `logo_url`), so expose it here.
html_context = {'logo': html_logo}

# If true, the reST sources are included in the HTML build as _sources/name.
# The default is True.
html_copy_source = False
